# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository
# Add funding sources here if desired (open_collective, github, custom URLs, etc.)
